name: Test action
on: workflow_dispatch
jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim

    steps:
    - name: checkout tag
      id: CT
      uses: actions/checkout@v4
      with:
        ref: 'v1.34.1'
    # - id: get_tag
    #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: echo tag
      run: echo ${{ steps.CT.with.ref }}
