name: Test action
on: workflow_dispatch
jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim

    steps:
    - name: checkout tag
      id: CT
      uses: actions/checkout@v4
      with:
        ref: '1.34.1'
    - name: Test
      run: |
        echo $INPUT_REF
        echo ${{ env.INPUT_REF }}
        echo ${{ steps.CT }}
        echo ${{ steps.CT.INPUT_REF }}
        echo ${{ steps.CT.with.INPUT_REF }}
