name: Test action
on: workflow_dispatch
jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim

    steps:
    - name: Set output
      id: So
      run: echo "::set-output so::123"
    - name: Get output
      run: echo ${{ steps.So.outputs.so }}
      
    - name: Set envoutput
      id: Seo
      run: echo "so=456" >> $GITHUB_OUTPUT
    - name: Get envoutput
      run: echo ${{ steps.Seo.outputs.so }}
      
    - name: Set env
      id: Se
      run: echo "so=568" >> $GITHUB_ENV
    - name: Get env
      run: echo $so
