name: Test action
on: workflow_dispatch
jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim

    steps:
    - name: checkout tag
      uses: actions/checkout@v4
      with:
        ref: '1.34.1'
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
