name: Test action
on: workflow_dispatch
jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim

    steps:
    - name: checkout tag
      id: CT
      uses: actions/checkout@v4
      with:
        ref: '1.34.1'
    - name: Test
      run: |
        echo $INPU_ref
        echo ${{ env.INPU_ref }}
        echo ${{ steps.CT.INPU_ref }}
        echo ${{ steps }}
